# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Beebuck' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Add the Firebase pod for Google Analytics
  pod 'Firebase/Analytics'

  # Add the pod for Firebase Cloud Messaging
  pod 'Firebase/Messaging'

  target 'BeebuckTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'Beebuck-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Beebuck-tvOS

  target 'Beebuck-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
